# Generated by Django 5.0.4 on 2024-04-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boxdata", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="boxdata",
            table="dataset_mapping",
        ),
    ]
