# Generated by Django 5.0.4 on 2024-04-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wellsdb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="hifldOilRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objectid", models.CharField(blank=True, max_length=50, null=True)),
                ("refid", models.CharField(blank=True, max_length=50, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("county", models.CharField(blank=True, max_length=50, null=True)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("naics_code", models.CharField(blank=True, max_length=50, null=True)),
                ("naics_desc", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "operatorname",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("capacity", models.CharField(blank=True, max_length=50, null=True)),
                ("us_rank", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "hifld_oilrefineries",
                "managed": False,
            },
        ),
    ]
