# Generated by Django 5.0.4 on 2024-04-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wellsdb", "0002_hifldoilref"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoxData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objectid", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "hifld_oilrefineries",
                "managed": False,
            },
        ),
    ]
