# Generated by Django 5.0.4 on 2024-04-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wellsdb", "0003_boxdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objectid", models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                "db_table": "plants_cracker",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TermPetro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objectid", models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                "db_table": "terminals_petrolium",
                "managed": False,
            },
        ),
    ]
