# Generated by Django 4.2.13 on 2024-05-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allegheny', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('record_type', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('geomjson', models.CharField()),
            ],
        ),
    ]
