# Generated by Django 4.2.13 on 2024-05-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allegheny', '0002_parcels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcels',
            options={'managed': False},
        ),
    ]
