# Generated by Django 4.2.13 on 2024-05-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allegheny', '0005_points'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wells15',
            table='wellsdb',
        ),
    ]
