# Generated by Django 5.0.4 on 2024-06-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allegheny', '0006_alter_wells15_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolygonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geomjson', models.CharField()),
                ('field_2', models.CharField(max_length=100)),
                ('field_5', models.CharField(max_length=100)),
                ('propertycity', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'your_polygon_table',
                'managed': False,
            },
        ),
    ]
