# Generated by Django 5.0.4 on 2024-06-06 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allegheny', '0007_polygonmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='polygonmodel',
            table='allegheny_parceldata4326_dis',
        ),
    ]
