# Generated by Django 4.2.13 on 2025-01-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geomjson', models.CharField(max_length=255)),
                ('statename', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'counties_json',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geomjson', models.CharField(max_length=255)),
                ('statename', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'states_json',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wells',
            fields=[
                ('api_num', models.CharField(blank=True, max_length=50, null=True)),
                ('other_id', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('stusps', models.CharField(blank=True, max_length=50, null=True)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('municipality', models.CharField(blank=True, max_length=50, null=True)),
                ('well_name', models.CharField(blank=True, max_length=50, null=True)),
                ('operator', models.CharField(blank=True, max_length=50, null=True)),
                ('spud_date', models.CharField(blank=True, max_length=50, null=True)),
                ('plug_date', models.CharField(blank=True, max_length=50, null=True)),
                ('well_type', models.CharField(blank=True, max_length=50, null=True)),
                ('well_status', models.CharField(blank=True, max_length=50, null=True)),
                ('well_configuration', models.CharField(blank=True, max_length=50, null=True)),
                ('ft_category', models.CharField(blank=True, max_length=50, null=True)),
                ('wellwiki', models.CharField(blank=True, max_length=50, null=True)),
                ('ftuid', models.IntegerField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'wells_natl_v1',
                'managed': False,
            },
        ),
    ]
