# Generated by Django 4.2.13 on 2025-01-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=50)),
                ('statename', models.CharField(max_length=20)),
                ('stusps', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'county_wstate',
                'managed': False,
            },
        ),
    ]
