# Generated by Django 5.0.4 on 2024-07-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0002_wells_delete_wells15'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wells',
            table='wells_20240701',
        ),
    ]
