# Generated by Django 4.2.13 on 2025-01-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0002_countynames'),
    ]

    operations = [
        migrations.CreateModel(
            name='stStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_status', models.CharField(max_length=50)),
                ('stusps', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'wellstatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='stType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_type', models.CharField(max_length=50)),
                ('stusps', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'welltype',
                'managed': False,
            },
        ),
    ]
