# Generated by Django 5.0.4 on 2024-07-17 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0003_alter_wells_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wells',
            table='wells_240701',
        ),
    ]
