# Generated by Django 5.0.4 on 2024-07-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0007_counties_states'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='states',
            table='states_json',
        ),
    ]
