# Generated by Django 4.2.13 on 2025-04-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wells',
            table='"wells"."wells"',
        ),
    ]
