# Generated by Django 4.2.13 on 2025-08-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0002_alter_wells_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
