# Generated by Django 4.2.13 on 2025-09-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0005_downloadlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadlog',
            options={'managed': False, 'ordering': ['-download_date']},
        ),
    ]
