# Generated by Django 5.0.7 on 2025-09-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0006_alter_downloadlog_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='downloadlog',
            table='"portals"."wells_downloads"',
        ),
    ]
